FROM microsoft/dotnet:2.1-sdk-stretch-arm32v7
 
ARG VSTS_AGENT_VERSION=2.168.0

# Install curl, wget and git
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git
 
# Download compiles vsts-agent
# See https://github.com/Microsoft/azure-pipelines-agent/releases
RUN curl 'https://vstsagentpackage.azureedge.net/agent/'$VSTS_AGENT_VERSION'/vsts-agent-linux-arm-'$VSTS_AGENT_VERSION'.tar.gz' -o vsts-agent.tar.gz \
    && mkdir vsts-agent \
    && tar xzf vsts-agent.tar.gz -C ./vsts-agent \
    && rm vsts-agent.tar.gz
 
# install node
RUN curl -sL https://deb.nodesource.com/setup_8.x \
    && apt-get install -y nodejs

COPY vsts.sh .

ENTRYPOINT [ "/bin/bash", "./vsts.sh" ]

